### ISSUE TITLE
[BUFR Converter] Update YAMLs for ATMS and AMSU-A so the IODA files generated can work with UFO seamlessly

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#1220]
## Description

Update YAMLs for ATMS and AMSU-A so the IODA files generated can work with UFO seamlessly

##To-Do 
**Configuration**
- test date is 2021080100 
- Use antenna temperature (Ta)
- ATMS is FFT remapped

**Test using fv3jedi_hofx_nomodel.x with the IODA files converted from BUFR converter**  
- Convert BUFR to IODA format using bufr2ioda.x with YAML
- Transform FV3 background to GeoVaL
- Run UFO HofX
- Run UFO HofX with QC (without thinning) 

**Check List**

BUFR Converter YAML -- Updated YAML files are in [feature/iodaconv_gdasapp](https://github.com/JCSDA-internal/ioda-converters/tree/feature/iodaconv_gdasapp)
- [x] [ATMS YAML](https://github.com/JCSDA-internal/ioda-converters/blob/feature/iodaconv_gdasapp/test/testinput/bufr_ncep_atms_ta_remap.yaml)  
- [x] [AMSUA (all except n15) YAML](https://github.com/JCSDA-internal/ioda-converters/blob/feature/iodaconv_gdasapp/test/testinput/bufr_ncep_1bamua_ta.yaml)
        Note: AMSUA n15 BUFR contains brightness temperature 

Investigate diag output from UFO 
- [x] ATMS HofX
- [x] ATMS HofX + QC
- [x] AMSUA HofX
- [x] AMSUA HofX + QC

**Comment by emilyhcliu** [comment]
### ATMS
### Sanity Check for ATMS Remapping (using Channel 10 as an example)

**Original O-F (no bias correction) --- Channel 10**
![atms_npp_ta_hofx_nbc_channel10](https://user-images.githubusercontent.com/36091766/232258354-280187a0-a7fa-4ec1-be1e-df2609c941e2.png)

**Remapped O-F (no bias correction) --- Channel 10**
![atms_npp_ta_remap_hofx_nbc_channel10](https://user-images.githubusercontent.com/36091766/232258364-6bdd0820-9635-4a38-a46b-175ff912b2bc.png)

### Check UFO diagnostic output (using channels 2 and 10 as examples)

**Remapped O-F with Bias Correction --- Channel 10**
![atms_npp_ta_remap_hofx_channel10](https://user-images.githubusercontent.com/36091766/232258418-f15f4489-6e3a-40a7-8235-cc8f71c80924.png)

**Remapped O-F with Bias Correction + QC  --- Channel 10**
![atms_npp_ta_remap_hofx_qc_channel10](https://user-images.githubusercontent.com/36091766/232258429-698e26d8-9673-4c7e-bd68-7d5d96bd0ac1.png)


**Remapped O-F without Bias Correction --- Channel 2**
![atms_npp_ta_remap_hofx_nbc_channel2](https://user-images.githubusercontent.com/36091766/232258463-3993b3e7-78a0-407d-b47d-f795ec852ffe.png)

**Remapped O-F with Bias Correction --- Channel 2**
![atms_npp_ta_remap_hofx_channel2](https://user-images.githubusercontent.com/36091766/232258470-217d6edb-6533-4bf6-9016-9781fce5f2dd.png)

**Remapped O-F with Bias Correction + QC --- Channel 2**
![atms_npp_ta_remap_hofx_qc_channel2](https://user-images.githubusercontent.com/36091766/232258472-0165f130-316a-417b-afb4-8ef0aa246a37.png)

### UFO work needs to be completed before testing the cycling of bias correction:
1. Add the antenna pattern weighted surface properties in each FOV (Check with JCSDA for a valid branch for testing)  --- 2nd priority
2. Add data thinning --- 1st priority

**Comment by emilyhcliu** [comment]
### AMSU-A

### Check UFO diagnostic output (using channels 2 and 9 as examples)
**O-F without bias correction --- Channel 9**
![amsua_n19_ta_hofx_nbc_channel9](https://user-images.githubusercontent.com/36091766/232262794-490f7f47-e113-4170-a704-a94b0c5a39e6.png)

**O-F with Bias Correction --- Channel 9**
![amsua_n19_ta_hofx_channel9](https://user-images.githubusercontent.com/36091766/232262806-cad1f4ea-3c53-4fce-8754-05f5b1da2f3f.png)

**O-F with Bias Correction + QC  --- Channel 9**
![amsua_n19_ta_hofx_qc_channel9](https://user-images.githubusercontent.com/36091766/232262813-16121fbf-eb41-48b3-84cd-91db587cfacb.png)

**O-F without Bias Correction --- Channel 2**
![amsua_n19_ta_hofx_nbc_channel2](https://user-images.githubusercontent.com/36091766/232262821-6562c933-7909-4620-9750-1549e4e62674.png)

**O-F with Bias Correction --- Channel 2**
![amsua_n19_ta_hofx_channel2](https://user-images.githubusercontent.com/36091766/232262843-2387b314-83f0-492d-a493-dfd3eea5c965.png)

**O-F with Bias Correction + QC --- Channel 2**
![amsua_n19_ta_hofx_qc_channel2](https://user-images.githubusercontent.com/36091766/232262852-933d67ec-e04b-4966-ab8c-a14cdc250207.png)

### UFO work needs to be completed before testing the cycling of bias correction:
1. Add the antenna pattern weighted surface properties in each FOV (Check with JCSDA for a valid branch for testing)  --- 2nd priority
2. Add data thinning --- 1st priority
