### ISSUE TITLE
Test and Enhance BUFR-to-IODA YAML for AMSU-A (ATOVS)

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#422]
## Description

**Create YAML file that maps the BUFR Mnenomics to Unified IODA Names for AMSU-A (ATOVS) and validate the IODA output**

Working branch: [feature/query_tovs](https://github.com/JCSDA-internal/ioda-converters/tree/feature/query_tovs)

**To-do list**
- [x] Create [YAMLs](https://github.com/jcsda-internal/ioda-converters/issues/422#issuecomment-894264427) for AMSU-A
- [x] Test YAMLs  
- [x] Add reading/writing capability of DB AMSU-A/MHS data in BUFR2NC Fortran Utility ([code changes](https://github.com/JCSDA-internal/ioda-converters/commit/28e95609658fbadeaea83d4420907dbf9eae3f09#diff-14f22418de0f8e3a78be829acc18b1bbd2851450135e734d012487f0394dff7a))
- [x] Result/Validation ([plots](https://github.com/jcsda-internal/ioda-converters/issues/422#issuecomment-894273603))

---

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of this issue.

What problem needs to be fixed? What new capability needs to be added?

If this is a bug, describe the current behavior.

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

What must be done before this can be done?
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - add this issue as a dependency to other ZenHub issues as appropriate

**Comment by emilyhcliu** [comment]
[IODA-GSI Comparison](https://docs.google.com/presentation/d/1KCmnZZRrmnitqlBOiLMGcRMfTDTjL4TmNjz7kWVTbno/edit?usp=sharing)

**Comment by emilyhcliu** [comment]
```
# (C) Copyright 2021 UCAR
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.

observations:
  - obs space:
      name: bufr
      obsdatain: "./testinput/2020110112/gdas.t12z.1bamua.tm00.bufr_d"
      mnemonicSets:
        - mnemonics: [YEAR, MNTH, DAYS, HOUR, MINU, CLAT, CLON]
        - mnemonics: [SAID, SIID, FOVN, SAZA, SOZA, BEARAZ, SOLAZI]
        - mnemonics: [CHNM, TMBR]
          channels: 1-15

      exports:
        splits:
          satId:
            category:
              mnemonic: SAID
              map:
                _3: metop-b
                _4: metop-a
                _5: metop-c
                _206: noaa-15
                _209: noaa-18
                _223: noaa-19
        variables:
          timestamp:
            datetime:
              year: YEAR
              month: MNTH
              day: DAYS
              hour: HOUR
              minute: MINU
          latitude:
            mnemonic: CLAT
          longitude:
            mnemonic: CLON
          satelliteId:
            mnemonic: SAID
          sensorID:
            mnemonic: SIID
          channelNumber:
            mnemonic: CHNM
          fieldOfViewNumber:
            mnemonic: FOVN
          solarZenithAngle:
            mnemonic: SOZA
          solarAzimuthAngle:
            mnemonic: SOLAZI
          sensorZenithAngle:
            mnemonic: SAZA
          sensorAzimuthAngle:
            mnemonic: BEARAZ
          brightnessTemperature:
            mnemonic: TMBR

    ioda:
      backend: netcdf
#     obsdataout: "./testrun/2020110112/gdas.t12z.1bamua.tm00.nc"
      obsdataout: "./testrun/2020110112/gdas.t12z.1bamua.tm00.{splits/satId}.nc"

      dimensions:
        - name: "nlocs"
          size: variables/brightnessTemperature.nrows
        - name: "nchans"
          size: variables/brightnessTemperature.ncols

      globals:
        - name: "MetaData/platformCommonName"
          type: string
          value: "AMSUA"

        - name: "MetaData/platformLongDescription"
          type: string
          value: "MTYP 021-023 PROC AMSU-A 1B Tb (NOAA-15-19, METOP-1,2)"

        - name: "MetaData/sensorCentralFrequency"
          type: floatVector
          value: [23.8, 31.4, 50.3, 52.8, 53.596, 54.4, 54.94, 55.5, 57.290,
                  57.290, 57.290, 57.290, 57.290, 57.290, 89.0]

      variables:
        - name: "MetaData/satelliteId"
          source: variables/satelliteId
          dimensions: ["nlocs"]
          longName: "Satellite identification"
          units: ""

        - name: "MetaData/channelNumber"
          source: variables/channelNumber
          dimensions: ["nchans"]
          longName: "Channel number"
          units: ""

        - name: "MetaData/latitude"
          source: variables/latitude
          dimensions: ["nlocs"]
          longName: "Latitude"
          units: "degrees_north"
          range: [-90, 90]

        - name: "MetaData/longitude"
          source: variables/longitude
          dimensions: ["nlocs"]
          longName: "Longitude"
          units: "degrees_east"
          range: [-180, 180]

        - name: "MetaData/datetime"
          source: variables/timestamp
          dimensions: ["nlocs"]
          longName: "Datetime"
          units: "datetime"

        - name: "MetaData/fieldOfViewNumber"
          source: variables/fieldOfViewNumber
          dimensions: ["nlocs"]
          longName: "Field of view number"
          units: ""

        - name: "MetaData/solarZenithAngle"
          source: variables/solarZenithAngle
          dimensions: ["nlocs"]
          longName: "Solar zenith angle"
          units: "degrees"
          range: [0, 180]

        - name: "MetaData/solarAzimuthAngle"
          source: variables/solarAzimuthAngle
          dimensions: ["nlocs"]
          longName: "Solar azimuth angle"
          units: "degrees"
          range: [0, 360]

        - name: "MetaData/sensorZenithAngle"
          source: variables/sensorZenithAngle
          dimensions: ["nlocs"]
          longName: "Sensor zenith angle"
          units: "degrees"
          range: [0, 90]

        - name: "MetaData/sensorAzimuthAngle"
          source: variables/sensorAzimuthAngle
          dimensions: ["nlocs"]
          longName: "Sensor azimuth angle"
          units: "degrees"
          range: [0, 360]

        - name: "ObsValue/brightnessTemperature"
          coordinates: "longitude latitude nchans"
          source: variables/brightnessTemperature
          dimensions: ["nlocs", "nchans"]
          longName: "Brightness temperature"
          units: "K"
          range: [120, 500]
          chunks: [1000, 15]
          compressionLevel: 4
```

**Comment by emilyhcliu** [comment]
```
# (C) Copyright 2021 UCAR
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.

observations:
  - obs space:
      name: bufr
      obsdatain: "./testinput/2020110112/gdas.t12z.esamua.tm00.bufr_d"
      mnemonicSets:
        - mnemonics: [YEAR, MNTH, DAYS, HOUR, MINU, CLATH, CLONH]
        - mnemonics: [SAID, SIID, FOVN, SAZA, SOZA, BEARAZ, SOLAZI]
        - mnemonics: [INCN, TMBRST]
          channels: 1-15

      exports:
        splits:
          satId:
            category:
              mnemonic: SAID
              map:
                _3: metop-b
                _4: metop-a
                _5: metop-c
                _206: noaa-15
                _209: noaa-18
                _223: noaa-19
        variables:
          timestamp:
            datetime:
              year: YEAR
              month: MNTH
              day: DAYS
              hour: HOUR
              minute: MINU
          latitude:
            mnemonic: CLATH
          longitude:
            mnemonic: CLONH
          satelliteId:
            mnemonic: SAID
          sensorID:
            mnemonic: SIID
          channelNumber:
            mnemonic: INCN
          fieldOfViewNumber:
            mnemonic: FOVN
          solarZenithAngle:
            mnemonic: SOZA
          solarAzimuthAngle:
            mnemonic: SOLAZI
          sensorZenithAngle:
            mnemonic: SAZA
          sensorAzimuthAngle:
            mnemonic: BEARAZ
          brightnessTemperature:
            mnemonic: TMBRST

    ioda:
      backend: netcdf
#     obsdataout: "./testrun/2020110112/gdas.t12z.esamua.tm00.nc"
      obsdataout: "./testrun/2020110112/gdas.t12z.esamua.tm00.{splits/satId}.nc"

      dimensions:
        - name: "nlocs"
          size: variables/brightnessTemperature.nrows
        - name: "nchans"
          size: variables/brightnessTemperature.ncols

      globals:
        - name: "MetaData/platformCommonName"
          type: string
          value: "AMSUA"

        - name: "MetaData/platformLongDescription"
          type: string
          value: "MTYP 021-033 RARS(EARS,AP,SA) AMSU-A 1C Tb DATA(N15-19))"

        - name: "MetaData/sensorCentralFrequency"
          type: floatVector
          value: [23.8, 31.4, 50.3, 52.8, 53.596, 54.4, 54.94, 55.5, 57.290,
                  57.290, 57.290, 57.290, 57.290, 57.290, 89.0]

      variables:
        - name: "MetaData/satelliteId"
          source: variables/satelliteId
          dimensions: ["nlocs"]
          longName: "Satellite identification"
          units: ""

        - name: "MetaData/channelNumber"
          source: variables/channelNumber
          dimensions: ["nchans"]
          longName: "Channel number"
          units: ""

        - name: "MetaData/latitude"
          source: variables/latitude
          dimensions: ["nlocs"]
          longName: "Latitude"
          units: "degrees_north"
          range: [-90, 90]

        - name: "MetaData/longitude"
          source: variables/longitude
          dimensions: ["nlocs"]
          longName: "Longitude"
          units: "degrees_east"
          range: [-180, 180]

        - name: "MetaData/datetime"
          source: variables/timestamp
          dimensions: ["nlocs"]
          longName: "Datetime"
          units: "datetime"

        - name: "MetaData/fieldOfViewNumber"
          source: variables/fieldOfViewNumber
          dimensions: ["nlocs"]
          longName: "Field of view number"
          units: ""

        - name: "MetaData/solarZenithAngle"
          source: variables/solarZenithAngle
          dimensions: ["nlocs"]
          longName: "Solar zenith angle"
          units: "degrees"
          range: [0, 180]

        - name: "MetaData/solarAzimuthAngle"
          source: variables/solarAzimuthAngle
          dimensions: ["nlocs"]
          longName: "Solar azimuth angle"
          units: "degrees"
          range: [0, 360]

        - name: "MetaData/sensorZenithAngle"
          source: variables/sensorZenithAngle
          dimensions: ["nlocs"]
          longName: "Sensor zenith angle"
          units: "degrees"
          range: [0, 90]

        - name: "MetaData/sensorAzimuthAngle"
          source: variables/sensorAzimuthAngle
          dimensions: ["nlocs"]
          longName: "Sensor azimuth angle"
          units: "degrees"
          range: [0, 360]

        - name: "ObsValue/brightnessTemperature"
          coordinates: "longitude latitude nchans"
          source: variables/brightnessTemperature
          dimensions: ["nlocs", "nchans"]
          longName: "Brightness temperature"
          units: "K"
          range: [120, 500]
          chunks: [1000, 15]
          compressionLevel: 4
                                                                                                                                   159,1         Bot
```

**Comment by emilyhcliu** [comment]
Update IODA-bundle to use feature/query
Add new YAML file for [normal feed](https://github.com/JCSDA-internal/ioda-converters/blob/feature/query_tovs/test/testinput/bufr_1bamua.yaml) and [direct broadcast](https://github.com/JCSDA-internal/ioda-converters/blob/feature/query_tovs/test/testinput/bufr_esamua.yaml) AMSU-A data

**Comment by emilyhcliu** [comment]
Add read/write capability for direct broadcast AMSU-A data in BUFR2NC Fortran Utility ([code changes](https://github.com/JCSDA-internal/ioda-converters/commit/28e95609658fbadeaea83d4420907dbf9eae3f09#diff-14f22418de0f8e3a78be829acc18b1bbd2851450135e734d012487f0394dff7a))

**Comment by emilyhcliu** [comment]
### Result and Validation

![test-feature_query](https://user-images.githubusercontent.com/36091766/128520116-a23d0310-3590-4e52-afd2-ab7537d0cc41.png)

![test-feature_query (1)](https://user-images.githubusercontent.com/36091766/128520135-866b0d16-2214-4c2b-bb5a-6ca5e53c15bf.png)
