### ISSUE TITLE
NOAA EMC BUFR to IODA Conversion Software Support and Enhancement for Satellite Radiances

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#428]
## Description

**This Epic is to support and enhance the BUFR to IODA (bufr2ioda) conversion software development (Epic #425) through the following work for [sensors used in the current GDAS operational system](https://docs.google.com/presentation/d/1Oi8LjeBFYlRjKOGcXcwWsjfY42qcoK8cr51DR9ofkDE/edit?usp=sharing)** :

- Extract BUFR Mnemonics and related information (variable definition, dimension, and unit) used by GDAS analysis (GSI) from the BUFR file
- Create variable mappings between BUFR Mnemonics and the [**Unified IODA Naming Convention**](https://docs.google.com/document/d/1F8-7pqvTyyQ_wuJsPmBORKxrnRipTRoZhrTB0XybLJc/edit?usp=sharing)
- Maintain the YAML file that contains the mapping information between the BUFR Mnemonics (input) and the Unified IODA Naming Convention (output) for each sensor.
- Test the bufr2ioda conversion software with the YAML file for each sensor 
- Verify the conversion for each sensor
- Enhance the bufr2ioda software if desired

**To-do List**

**1. List mapping between BUFR mnemonics and IODA names**
- [x] Create a google spreadsheet that documents the [mapping between BUFR Mnemonics and the Unified IODA** names](https://drive.google.com/file/d/1c0b3FoaAA_7XI0PwQkXZM9zPzbQWgDVQ/view?usp=sharing)  (Issue #430) 

**Note**: For BUFR dump file, unified IODA names can be found from [WMO BUFR Element Table] (https://confluence-test.ecmwf.int/display/ECC/WMO%3D35+element+table) based on the FXXYYY assigned to each BUFR MNEMONIC

**2. Validate and enhance the following YAML files developed by PR #473** 
- [x] AMSU-A
- [x] AMSU-A (DB/EARS)
- [ ] EOS AMSU-A (AQUA)
- [ ] ATMS
- [x] MHS
- [x] MHS (DB/EARS)
- [ ] SSMIS
- [ ] AIRS

**3. Create, test and enhance YAMLs for each sensor listed below:**
- [ ] SAPHIR
- [x] IASI
- [ ] CrIS
- [ ] AVHRR
- [ ] SEVIRI

**Resources**

- [WMO OSCAR - List of All Instruments](https://www.wmo-sat.info/oscar/instruments)
- [WMO OSCAR - List of All Satellites](https://www.wmo-sat.info/oscar/satellites)
- [WMO BUFR Element Table](https://confluence-test.ecmwf.int/display/ECC/WMO%3D35+element+table)
- [ECMWF ODB Database](https://apps.ecmwf.int/odbgov/unionall/)
- [NOAA NCEP BUFR Tables](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/) and [Documentation](https://docs.google.com/presentation/d/1rk-LToVtoeau4gHprfd9r07vhp-ex-L1ak8hatAfU7U/edit?usp=sharing)
- [Conventions for JEDI Data v1.0.0 - Tables](https://docs.google.com/spreadsheets/d/1fHb2QIHOwgp4d6plyn9Dj9HZFZsDRxcPaUV6hdTb5BU/edit?usp=sharing)

---

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of this issue.

What problem needs to be fixed? What new capability needs to be added?

If this is a bug, describe the current behavior.

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

What must be done before this can be done?
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - add this issue as a dependency to other ZenHub issues as appropriate

**Comment by gthompsnJCSDA** [comment]
@emilyhcliu   We have a lot of overlap in our tracking of issues related to bufr2ioda.  From my work with Nan, I believe we should now close issues #403  #422  #423  as they are duplicated by our issue #899 along with our PR #473.  Therefore we can easily collapse this Epic and just follow up with issue #474  which are the remaining satellite platforms not covered in the PR.  Would you agree Emily?

**Comment by emilyhcliu** [comment]
@gthompsnJCSDA I will keep #403 #422 and #423 and change their objectives to do tests and enhancement using YAMLS from PR #473 from our ends.

**Comment by symoore90** [comment]
Closing because epic is completed
