### ISSUE TITLE
NOAA EMC Marine Data to IODA Conversion Software Support and Enhancement

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#433]
## Description

Convert SFCSHP from Prepbufr and Dump to IODA files

[Task List](https://docs.google.com/document/d/1xd6RKEWJIKdiXKIIBh9wx9Xjf-OxU8V3/edit)

To-do list:
- [ ] Create Yaml file for dbuoyb bufr file.
- [ ] Create Yaml file for mbuoyb bufr file.
- [ ] Create Yaml file for ship bufr file.
- [ ] Create Yaml file for argo and glider bufr file.
- [ ] Create small test file for testinput.

Resources:
[ObsProc Re-engineering Info](https://docs.google.com/presentation/d/1KYVI7TuH9y0JNPrjT4Q3YntczNzbH4yPi2Sl2Sb7g-Y/edit#slide=id.g104a1d553d4_0_98)
[SFCSHP ](https://docs.google.com/presentation/d/1A7Imn3fkhkHHEkU6zKrN5eVU_6YOLNt_W3mYC2Kb02E/edit#slide=id.gf0a35d8e39_0_266)
[NSST](https://docs.google.com/presentation/d/1RS8O9n41HLHztycWQ5UPYd5lEyXDr1RdvQRpm5goenc/edit#slide=id.gf086b43124_1_364)

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of this issue.

What problem needs to be fixed? What new capability needs to be added?

If this is a bug, describe the current behavior (or use the bug template).

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

What must be done before this can be done?
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - add this issue as a dependency to other ZenHub issues as appropriate

**Comment by YanHao-NOAA** [comment]
Found two issues with bufr2ioda.x:

- [ ] bufr2ioda.x can not read CCITT IA5 formatted variables correctly, string is read as float. (e.g., RPID, SHPC8 etc.)
- [ ] Some kind of variables can not be grouped together in yaml file, it seems that the variables within sequence which has { } sign can not combined with other variables. ( e.g., {WAVSQ3} contains => 'DOSW POSW HOSW', if we add any other variable in the same group with 'DOSW POSW HOSW':  e.g. , - mnemonics: [SST1, DOSW, POSW, HOSW],  the following error shows up:
 ***********BUFR ARCHIVE LIBRARY ABORT**************
 BUFRLIB: PARUSR - INPUT STRING (SST1 DOSW POSW HOSW) CONTAINS                  
                   STORE NODES (MNEMONICS) THAT ARE IN MORE THAN ONE REPLICATION GROUP
 ***********BUFR ARCHIVE LIBRARY ABORT**************
- mnemonics: [DOSW, POSW, HOSW] alone works okay.
- It seems those sequences with < > sign have no such problems.

**Comment by symoore90** [comment]
Closing because epic is completed
