### ISSUE TITLE
NOAA EMC BUFR to IODA Conversion Software Support and Enhancement for Satellite Derived AMV Winds

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#445]
### NCEP Satellite Atmospheric Motion Vector Winds
[NCEP SATWND (AMV) INFO](https://docs.google.com/presentation/d/1D44f69vNfuu8l7iHOw2IYvixN2bQlrLN4-cuW6RgNGY/edit?usp=sharing)

Satellite Wind dump file [BUFR table](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/bufrtab.005)

List of subset from satellite wind dump file
```
split_by_subset.x gdas.t00z.satwnd.tm00.bufr_d
################################################
    TYPE    MESSAGES       SUBSETS         BYTES
################################################
NC005044        1002         48901       9786404
NC005045         658         32199       6443788
NC005046        1101         53860      10778694
NC005067        5080        137125      50462070
NC005068         604         16256       5982312
NC005069        8456        228215      83983314
NC005070          53          3478        482826
NC005071          61          4248        589518
NC005080         184         12512       1736592
NC005091         250         55385       2455070
NC005024        1693         82808      16571904
NC005025          12           549        109910
NC005026        1213         59269      11861244
NC005030        2131        506016      21211580
NC005031         473        125244       4687526
NC005032        5592       1606545      55726432
NC005034         882        217882       8770618
NC005039         223         57281       2178790
------------------------------------------------
   TOTAL       29668       3247773     293818592
################################################
```
### List of Tasks
**Create YAML/IODA files based on platform and algorithm**
**HIMIWARI Series** 1-9 (GSM 1-5, MTSAT 6-7, HIMARAWI 8-9)
- [ ] NC005044   HIMAWARI IRLW
- [ ] NC005045   HIMAWARI VIS
- [ ] NC005046   HIMAWARI WVCT

**GOES series** 16-17
- [ ] NC005039   GOES IRSW
- [ ] NC005300   GOES IRLW
- [ ] NC005034   GOES WVCT 
- [ ] NC005031   GOES WVCA 
- [ ] NC005032   GOES VIS

**MeteoSat series** 8-11
- [ ] NC005064   SEVIRI IRLW
- [ ] NC005065   SEVIRI VIS
- [ ] NC005066   SEVIRI WV (CT/CA)
 
**AQUA/TERRA series**
- [ ] NC005070    MODIS IRLW
- [ ] NC005071     MODIS WV(CT/CA)

**JPSS series** 
- [ ] NC005091     VIIRS IRLW

 **POES series** (NOAA 15-19 and MetOp A-C)
- [ ] NC005080     AVHRR IRLW

**Comment by ilianagenkova** [comment]
@AshleyStanfield-NOAA @ilianagenkova  continued development of BUFR2IODA conversion for Satellite AMVs, using feature/query automatic dimensions query code (a branch under https://github.com/JCSDA-internal/ioda-converters).

Progress was made on the YAML file, the challenge being handling two-dimensional data. 
/scratch1/NCEPDEV/da/Ashley.Stanfield/feat_query/yaml_test/SatWnd_Old_NC005604.yaml

**Comment by symoore90** [comment]
Closing because epic is completed
