### ISSUE TITLE
NOAA EMC PrepBUFR to IODA Conversion Software Support and Enhancement for Conventional ADPSFC Data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#449]
### NCEP ADPSFC Data

[NCEP PrepBUFR Table](https://github.com/JCSDA-internal/ioda-converters/blob/develop/doc/bufr_table_samples/adpupa.prepbufr.table.txt)

[NCEP ADPSFC INFO](https://docs.google.com/presentation/d/1N8wfLI6cmYB7oeESu_YTjaVQU11iadbcIVx48geeH2M/edit?usp=sharing)

### List of Tasks
- [ ] Create YAML file for ADPSFC PrepBUFR
- [ ] Validate with Reference data from GSI
- [ ] Create unit test data with reduced size
