### ISSUE TITLE
NOAA EMC BUFR to IODA Conversion Software Support and Enhancement for Conventional ADPSFC Data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#452]
### NCEP ADPSFC Data

[NCEP ADPSFC BUFR Table ](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/bufrtab.000)

[NCEP ADPSFC INFO](https://docs.google.com/presentation/d/1N8wfLI6cmYB7oeESu_YTjaVQU11iadbcIVx48geeH2M/edit?usp=sharing)

### List of Tasks
- [ ] Create YAML file for ADPSFC BUFR
- [ ] Validate with Reference data from GSI
- [ ] Create unit test data with reduced size

**Comment by symoore90** [comment]
Closing because epic is completed
