### ISSUE TITLE
NOAA EMC BUFR to IODA Conversion Software Support and Enhancement for Conventional ADPUPA Data 

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#453]
### NCEP ADPUPA Data

[NCEP ADPUPA BUFR Table](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/bufrtab.002)

[NCEP ADPUPA Data Info](https://docs.google.com/presentation/u/0/d/1WBK4CCZceYzeN_C7W7a7mAZ9BdW9mPMfmzhWLVcDNyo/edit)

### List of Tasks

Create YAML files based on types
- [ ] ADPUPA - NC002001, NC002002, NC002003, NC002004, NC002005
- [ ] PROFLR - NC002009, NC002011
- [ ] VADWND - NC002008, NC002017
- [ ] RASSDA - NC002012
- [ ] RECON - NC04005

**Comment by symoore90** [comment]
Closing because epic is completed
