### ISSUE TITLE
NOAA EMC BUFR to IODA Conversion Software Support and Enhancement for Conventional AIRCAR/AIRCFT Data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#454]
### NCEP Aircraft Data

[NCEP Aircraft BUFR Table](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/bufrtab.004)

[NCEP Aircraft Data Info](https://docs.google.com/presentation/d/10y7vIYFl6M3sK27lrVcob63eCvvEoDWeBr2_tFyor_U/edit?usp=sharing)

[Observations in Aircraft BUFR Dump file - based on NC type](https://docs.google.com/spreadsheets/d/16WL50Kumgw_FFJ56q25yzMLFBDIGp8GCiOhJ8AW6cq0/edit#gid=724693400) (spreadsheet)

Two aircraft dump files: ($hh= 00 06 12 18)
AIRCAR: gdas.t${hh}z.aircar.tm00.bufr_d  - NC004004
AIRCFT: gdas.t${hh}z.aircft.tm00.bufr_d  - NC004001, 002, 003, 006, 009, 010, 011, 103

### List of Tasks
Create YAML files based on the following grouping: (initial attempt)
- [ ] Type 130 - NC004001 + NC004002
- [ ] Type 131 - NC004003 + NC004006 + NC004011 + NC004103
- [ ] Type 133 - NC004004 (This is AIRCAR)
- [ ] Type 134 - NC004010
- [ ] Type 135 - NC004009

Alternative is to combine subsets into two groups:
- [x] AIRCAR - NC004004
- [x] AIRCFT -  NC004001 + NC004002 + NC004003 + NC004006 + NC004009 + NC004010 + NC004011 + NC004103

**Comment by nicholasesposito** [comment]
We ended up going with the alternative and added 3 yamls. AIRCAR, AIRCFT without AMDAR, and only AMDAR.
