### ISSUE TITLE
NOAA EMC PREPBUFR to IODA Conversion Software Support and Enhancement for Conventional SFCSHIP Data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#494]
### NCEP Surface Ship Data Processing
[ObsProc Re-engineering Info](https://docs.google.com/presentation/d/1KYVI7TuH9y0JNPrjT4Q3YntczNzbH4yPi2Sl2Sb7g-Y/edit#slide=id.g104a1d553d4_0_98)

[NCEP PrepBUFR Table](https://github.com/JCSDA-internal/ioda-converters/blob/develop/doc/bufr_table_samples/adpupa.prepbufr.table.txt)

[NCEP SFCSHP Info ](https://docs.google.com/presentation/d/1A7Imn3fkhkHHEkU6zKrN5eVU_6YOLNt_W3mYC2Kb02E/edit#slide=id.gf0a35d8e39_0_266)

[NCEP NSST Info](https://docs.google.com/presentation/d/1RS8O9n41HLHztycWQ5UPYd5lEyXDr1RdvQRpm5goenc/edit#slide=id.gf086b43124_1_364)

 
### List of Tasks ([Task List](https://docs.google.com/document/d/1xd6RKEWJIKdiXKIIBh9wx9Xjf-OxU8V3/edit))
- [ ] Create YAML file for SFCSHP data from PrepBufr
- [ ] Validate IODA output with reference data from GDAS
- [ ] Create test data with reduced size

**Comment by YanHao-NOAA** [comment]
Created prepbufr_sfcshp.yaml, applied bufr2ioda.x to create sfcshp-prepbufr.nc.
All the variable values are missing values. It seems bufr2ioda.x is not working on SFCSHP prepbufr file directly at this moment.

**Comment by YanHao-NOAA** [comment]
Prepbufr SFCSHP file needs to be split into several bufr files.

**Comment by symoore90** [comment]
Closing due to lack of activity.
