### ISSUE TITLE
NOAA EMC BUFR to IODA Conversion Software Support and Enhancement for Conventional SFCSHIP Data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#495]
### NCEP Surface Marine Data 
[ObsProc Re-engineering Info](https://docs.google.com/presentation/d/1KYVI7TuH9y0JNPrjT4Q3YntczNzbH4yPi2Sl2Sb7g-Y/edit#slide=id.g104a1d553d4_0_98)

[NCEP SFCSHP BUFR Table](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/bufrtab.001)

[NCEP SFCSHP INFO ](https://docs.google.com/presentation/d/1A7Imn3fkhkHHEkU6zKrN5eVU_6YOLNt_W3mYC2Kb02E/edit#slide=id.gf0a35d8e39_0_266)

[NCEP NSST INFO](https://docs.google.com/presentation/d/1RS8O9n41HLHztycWQ5UPYd5lEyXDr1RdvQRpm5goenc/edit#slide=id.gf086b43124_1_364)

[Task List in Google Drive](https://docs.google.com/document/d/1xd6RKEWJIKdiXKIIBh9wx9Xjf-OxU8V3/edit)

### List of Tasks
- [ ] Create YAML file for SFCSHP BUFR data
- [ ] Validate IODA output with reference data from GDAS
- [ ] Create test data with reduced size

**Comment by gthompsnJCSDA** [comment]
The issue description is a copy of the template and nothing really meaningful here.  Assuming it was created as a placeholder, but please edit the issue to describe.  Also, I have a starting WMO-BUFR format file and yaml for ship data.  I will be improving it ASAP and testing it.  It would be good to keep me in the loop on this item.

**Comment by huishao-r** [comment]
@emilyhcliu since the BUFR work is still going on in AOP22, I unlinked the subepics from AOP21 and we'll add new Epics for AOP22 later. I did the same thing for other NOAA subEpics as well. They stay under Obs subEpics for now. We'll discuss how to arrange them when AOP22 epics kick in.

**Comment by BenjaminRuston** [comment]
@emilyhcliu think we can actually close this one with the recent work which was completed

**Comment by emilyhcliu** [comment]
@BenjaminRuston Yes, this had been completed.  
Closing now.
